@baseUrl = http://localhost:8080

GET http://api.weatherapi.com/v1/current.json?key=0fb748d1b88e40cd93c162732240202&q=davao&aqi=no

###
GET  http://localhost:8080/weather
Content-Type: application/json

{

  "location": "davao"

}

###

POST {{baseUrl}}/user-register
Content-Type:  application/json

{
  "username": "mark",
  "password": "joseph",
  "email": "markjosephtiempo@gmail.com"
}

###

