@baseUrl = http://localhost:8080

GET http://api.weatherapi.com/v1/current.json?key=0fb748d1b88e40cd93c162732240202&q=davao&aqi=no

###
GET  http://localhost:8080/weather
Content-Type: application/json

{

  "location": "davao"

}

###

POST {{baseUrl}}/user-register
Content-Type:  application/json

{
  "username": "mark",
  "password": "joseph",
  "email": "markjosephtiempo@gmail.com"
}

###

GET {{baseUrl}}/decode-token
Authorization: Bearer "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im1hcmsiLCJwYXNzd29yZCI6Impvc2VwaCIsImVtYWlsIjoibWFya2pvc2VwaHRpZW1wb0BnbWFpbC5jb20iLCJpYXQiOjE3MDc2MzMyNDEsImV4cCI6MTcwNzYzNjg0MX0.-yl1VLvi81MaFTsxULf7SztmB5WjHfoQmY071FqG0io"